# Server
server.port=8080
# Thymeleaf configuration
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8
spring.cache.type=simple
#Environment
artifactsmmo.api.token=${API_TOKEN}
artifactsmmo.api.accountName=${API_ACCOUNTNAME}
#Logging
logging.file.name=logs/artifactmmo.log
logging.file.max-size=100MB
logging.file.max-history=10  # Optional: keep up to 10 archive files